version: '3'
services:
  movies-front:
    container_name: movies_front_container_tarea3
    build: movies-front
    command: npm start
    volumes:
      - ./movies-front:/usr/app
      - /usr/app/node_modules
    depends_on:
      - movies-api
    environment:
      - PORT=${REACT_PORT}
      - BIND_IP
      - BIND_PORT
      - REACT_APP_API_URI

    expose:
      - ${REACT_PORT}
    ports:
      - ${REACT_PORT}:${REACT_PORT}
   
  movies-api:
    container_name: movies_api_tarea3
    build: movies-api
    image: movies_api
    command: "/movies-api -b ${BIND_IP} -p ${BIND_PORT}"
    environment:
      - BIND_IP
      - BIND_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_SERVER
      
    expose:
      - ${BIND_PORT}
    ports:
      - ${BIND_PORT}:${BIND_PORT}
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres_tarea3
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
    expose:
      - ${POSTGRES_PORT}

  flyway:
    image: flyway/flyway:7
    container_name: migration_flyway_tarea3
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
      - FLYWAY_GROUP=true
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./sql_migrations:/flyway/sql
    depends_on:
      - postgres